name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        # pnpmを使うことでプロジェクト内部の依存関係を正しく解決します
        run: pnpm install --no-frozen-lockfile --ignore-pnpmfile

      - name: Build
        # プロジェクト全体のビルドを実行
        run: pnpm run build
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages